export const BASE_URL = "http://localhost:8000/";
export const REGISTER = "admin/register-user";
export const FETCHUSERS = "admin/fetch-users";
export const DELETEUSERS = (uid) => `admin/delete-user/${uid}`;
export const LOGINUSER = "users/login";
export const CMSDATA = "users/cms";
export const USERTEMPLATE = "users/template";
export const DELETEIMAGE = "users/delete-image";
export const BASEPATH = "/";
export const NEWUSERPATH = "/new-user";
export const INFOPATH = "/info";
export const IMAGESPATH = "/images";
export const TEAMPATH = "/team";
export const ANALYTICSPATH = "/analytics";
export const PAGENOTFOUNDURL = "*";
